config/base.py
lib/cut_functions.py
parameters/cuts/baseline_cuts.py
parameters/cuts/cut_definition.py
utils/Configurator.py
workflows/base.py

Only the Configurator save_config() needs to be fixed.

Debugging the new cut implementation

---

lib/cut_definition.py
parameters/cuts/baseline_cuts.py
utils/Configurator.py
workflows/base.py

Trying to improve on #3.
Now a set of Cuts is extracted from the list of Cuts and the name is used to check unicity. 
For the moment I would not constraint the Cut name to be the same as the object label. Anyway the categories can be defined dynamically in functions so the name of the Cut is just used in case we want to import them from external libraries. 
Thinking about how to export it properly (probably by creating a .pickle with the functions? if we need 1to1 reproducibility)

Check unicity of Cut object

---

config/base.py
datasets/datasets_definitions.json
scripts/dataset/build_dataset.py
utils/Configurator.py

Reorganized dataset handling.
Now the analysis cfg file contains just the list of the datasets json you want to run on and a filter by sample/year.
The dataset definition used by the build_dataset script are saved in a new json file.

Dataset config

---

notebooks/parton_matching_test.ipynb
notebooks/save_vectors.ipynb
workflows/base.py
workflows/mem.py

`process_extra()` for `before_presel()` and `after_presel()`. 
Added back also `fill_histograms_extra()`
---------------------------
Added minimum deltaR  to parton matching

Updates for extra function and more

---

lib/objects.py
notebooks/Jet_selection.ipynb
parameters/preselection.py
utils/Configurator.py
workflows/base.py

The different jet masks (preselections, lepton cleaning, puid) are precomputed and then applied. 
The final jet mask is also returned (it may be needed for scale factors). 
Separated btag selection from jet selection (for future expansion).
===============================
The PR improved the jet_selection timing. 
Workflow = parton_matching with 10k events.

Improved Jet selections

---

PocketCoffea/lib/deltaR_matching.py
PocketCoffea/workflows/parton_matching.py
README.md
config/parton_matching/config.py

Fixed problems with numba functions: now they get compiled only once. 
Running on Dask works well now.

Parton matching now working with Numba compiled functions on dask

---

PocketCoffea/lib/cut_functions.py
PocketCoffea/utils/Configurator.py
PocketCoffea/workflows/base.py
PocketCoffea/workflows/parton_matching.py
README.md
config/parton_matching/config.py
config/test_skim.py

Prepared some basic Cut generators to count objects for skim configuration.

Added some predefined cut function getters

---

PocketCoffea/utils/PlotEfficiency.py
PocketCoffea/utils/PlotUtils.py
config/test_plotting.py
scripts/plot/make_plots.py
scripts/plot/trigger_efficiency.py

A plotting script for 1D histograms is implemented. A histogram is plotted for each of the categories contained in the `cat` axis and for each data-taking year in the `year` axis. The data/MC ratio is also shown in the bottom subplot.
The MC systematic uncertainty is plotted on top of the MC stack in the histogram plot and around 1 in the ratio plot.
The uncertainty on data corresponds to the statistical uncertainty only.
At the moment, the systematic uncertainty includes the effect of the systematic variations only, while the systematic uncertainty associated with the MC weights (the "MC stat") is not included yet. This will be fixed in a future PR.

Plotting script implementation

---

config/base.py
config/semileptonic_triggerSF/semileptonic_triggerSF_2018.py
config/test_HLT_sel.py
pocket_coffea/parameters/object_preselection.py
pocket_coffea/parameters/triggers.py
pocket_coffea/utils/plot_efficiency.py
pocket_coffea/utils/plot_utils.py
pocket_coffea/workflows/semileptonic_triggerSF.py
scripts/plot/trigger_efficiency.py

The config files and parameters (triggers, object preselections) are updated in order to adapt to the newest scheme. The major change is in the definition of the trigger pass/fail categories and the renaming of the data samples.
Also the plotting scripts are debugged and fully functional.

Semileptonic trigger SF with new configuration

---

config/base.py
config/test_HLT_sel.py
config/test_subsamples.py
pocket_coffea/lib/cut_functions.py
pocket_coffea/lib/hist_manager.py
pocket_coffea/lib/jets.py
pocket_coffea/lib/leptons.py
pocket_coffea/lib/triggers.py
pocket_coffea/lib/weights_manager.py
pocket_coffea/parameters/triggers.py
pocket_coffea/parameters/xsec.py
pocket_coffea/utils/configurator.py
pocket_coffea/utils/logging.py
pocket_coffea/utils/plot_utils.py
pocket_coffea/workflows/base.py
pocket_coffea/workflows/tthbb_base_processor.py
scripts/runner.py
tests/test_hlt_cut.py

Adding the possibility to define subsamples as sample specific cuts. 
Histograms are created separately for each subsample.
```
"dataset" : {
"jsons": ["datasets/signal_ttHTobb_local.json",
"datasets/backgrounds_MC_TTbb_local.json",
"datasets/backgrounds_MC_ttbar_local.json",
"datasets/DATA_SingleMuon_local.json",
"datasets/DATA_SingleEle.json"],
"filter" : {
"samples": [
"TTbbSemiLeptonic",
],
"samples_exclude" : [],
"year": ['2018']
},
"subsamples": {
"TTbbSemiLeptonic":
{
"tt+3b": [get_nObj_eq(3, coll="BJetGood")],
"tt+4b": [get_nObj_eq(4, coll="BJetGood")],
"tt+5b": [get_nObj_eq(5, coll="BJetGood")],
}
}
},
````

Subsamples implementation

---

pocket_coffea/lib/columns_manager.py

Currently, columns can only be made from object collections. This change allows for event level parameters to be stored in columns.

Update columns_manager.py to allow for branches using event parameters

---

pocket_coffea/parameters/histograms.py
pocket_coffea/utils/plot_utils.py

Implemented a couple of fixes to the plotting code:
- Update fatjet default histograms.
- Manage shapes with data only.
- `plot_datamc_all()` now plots data if only data, MC if only MC or data+MC if both exist.

Improved plotting

---

pocket_coffea/parameters/jet_scale_factors.yaml
pocket_coffea/parameters/lepton_scale_factors.yaml
pocket_coffea/parameters/variations.yaml

File name changes to keep Run 3 defaults up to date.

Run3 sf file name defaults

---

pocket_coffea/lib/jets.py
pocket_coffea/lib/leptons.py

Adding new variables important for VHcc analysis.
+BTV Commissioning. Soft lepton selection

VHcc analysis. Adding variables.

---

pocket_coffea/lib/jets.py
pocket_coffea/parameters/jets_calibration.yaml
pocket_coffea/workflows/base.py

Small corrections to JEC code for Run3

---

pocket_coffea/lib/scale_factors.py
pocket_coffea/scripts/runner.py

Various improvements to run in  the CAT weights validation CDCI

Changes for CAT weights CDCI

---

docs/running.md
pocket_coffea/executors/executors_infn_af.py
pocket_coffea/parameters/executor_options_defaults.yaml
pocket_coffea/scripts/runner.py

The PR adds an executor for the INFN Analysis Facility
FYI @ttedeschi

Add INFN AnalysisFacility executor

---

docs/running.md
pocket_coffea/executors/executors_RWTH.py
pocket_coffea/lib/gen_objects.py
pocket_coffea/lib/jets.py
pocket_coffea/parameters/executor_options_defaults.yaml

A working version of dask at RWTH linux cluster introduced.
Also, renamed get function for generator leptons and jets.

Introducing dask for RWTH executor

---

pocket_coffea/lib/hist_manager.py

In the HistManager, a cache of weights is kept to avoid recomputing them for different variables. 
Using dask I have observed a strage memory error related to this weight cache, which was living in a function closure. 
Making the dictionary fully local to the HistManager instance, the error has been solved. 
No changes expected in performance or on the user side.

Weights cache to local variable to avoid dask issues

---

pocket_coffea/parameters/histograms.py

Hotfix for jet_taggers_hists()

---

docs/running.md
pocket_coffea/executors/executors_base.py
pocket_coffea/executors/executors_brux.py
pocket_coffea/parameters/executor_options_defaults.yaml
pocket_coffea/scripts/runner.py

Adding support for the brux20 condor cluster at Brown University. Dask has been used for scaling. `dask@brux` should work now.

Support for dask at Brown brux20 cluster

---

pocket_coffea/parameters/plotting_style.yaml
pocket_coffea/utils/plot_utils.py

solves #255
the default parameters for plotting are set in the plotting_style.yaml file. In the initialization of the Style class, the yaml file is loaded and the parameters are updated with the user-defined values.

load plotting style defaults from yaml file

---

pocket_coffea/lib/leptons.py
pocket_coffea/parameters/lepton_scale_factors.yaml
pocket_coffea/workflows/base.py

Added a (very preliminary) implementation of nominal ele scale smearing. For working implementation of shifts, the handling of the shape variations needs to be changed, since the nominal values need to be saved.
Work in progress, iterating with @valsdav

Preliminary implementation of nominal ele scale smearing

---

pocket_coffea/workflows/base.py

Fixed random seed used in electron smearing to be positive.

Ele smearing rnd seed fix

---

.gitlab-ci.yml
Dockerfile
pocket_coffea/lib/jets.py
requirements.txt

This PR will be merged when the new dask-lxplus image will be merged to master.

Move apptainer images to Python 3.11 and newer dask

---

pocket_coffea/utils/plot_utils.py

It seems the code correctly blinds data in the upper canvas, but does not blind the ratio in the ratio plot. Moving the blinding task to a function and calling it at both data and ratio plotting levels.

Blind ratio plots when blinding data

---

docs/running.md
pocket_coffea/executors/executors_oscar.py
pocket_coffea/parameters/executor_options_defaults.yaml
pocket_coffea/scripts/runner.py

This also includes minor changes to the dask@brux executor defaults.

Adding executor for Oscar cluster @ Brown University (slurm based)

---

docs/installation.md
docs/running.md
pocket_coffea/utils/plot_utils.py

Minor fixes for documentation.

Improve docs for installation

---

docs/law_tasks.md
pocket_coffea/law_tasks/configuration/general.py
pocket_coffea/law_tasks/tasks/datasets.py
pocket_coffea/law_tasks/utils.py

- there was a typo in the documentation
task for plotting is called *Plotter*
- added missing docstring to a function

update documentation and docstring

---

pocket_coffea/parameters/plotting_style.yaml
pocket_coffea/utils/plot_utils.py

fix for #316
new default added
```yml
opts_ylim:
datamc:
ylim_log:
lo: 0.01
systematics:
ylim_log:
lo: 0.01
```

add missing default for ylim_log systematics

---

docs/running.md
pocket_coffea/executors/executors_CLAIX.py
pocket_coffea/parameters/executor_options_defaults.yaml
pocket_coffea/scripts/runner.py

Add a new dask executor on CLAIX

dask executor on CLAIX

---

pocket_coffea/lib/jets.py
pocket_coffea/lib/leptons.py

Added some variables for the kinematic fit in VHcc analysis. As well as calculation of the remnant vector for the same purpose

Kinematic_fit_for_VHcc

---

pocket_coffea/utils/plot_utils.py

This pull request to `pocket_coffea/utils/plot_utils.py` includes several changes to improve the handling of samples and systematic uncertainties in plotting utilities. The most important changes include adding new configuration options, modifying sample filtering logic, and enhancing systematic uncertainty handling.
* Added new configuration options `has_only_samples` and `has_order_mc` in the `__init__` method to handle specific sample filtering and ordering requirements.
* Replaced the `exclude_samples` method with a more flexible `filter_samples` method that can handle both inclusion and exclusion of samples based on the configuration.
* Added checks for empty systematic variations and improved the logic for handling missing variations in histograms.
* Implemented logic to order Monte …

Minor improvements in plotting

---

docs/analysis_example.md
docs/plots.md
pocket_coffea/scripts/plot/make_plots.py
pocket_coffea/utils/plot_utils.py

Add option to set x axis to log scale.

Add option to set x axis to log scale

---

pocket_coffea/workflows/base.py

Fix type error

---

pocket_coffea/scripts/runner.py

Fix #327 Events throughput is calculated incorrectly when using -ps option

Fix #327: fix incorrect throughput

---

pocket_coffea/executors/executors_DESY_NAF.py

A simple PR aiming to fix a few issues on the DESY-NAF executor for a proper setup
Cc: @matintorkian

Fixing DESY NAF executor

---

docs/running.md
pocket_coffea/executors/executors_DESY_NAF.py
pocket_coffea/executors/executors_base.py
pocket_coffea/parameters/executor_options_defaults.yaml
pocket_coffea/scripts/runner.py

Here are just some updates to run at DESY (with Parsl), mostly updating for more common parameters (memory, conda-env etc).
Plus some updates to documentation

Update paramers for DESY executor

---

docs/running.md
pocket_coffea/executors/executors_CLAIX.py
pocket_coffea/parameters/executor_options_defaults.yaml

@andreypz please test this on CLAIX before we mark ready : )

Parsl on CLAIX

---

pocket_coffea/lib/hist_manager.py
tests/test_full_configs/test_shape_variations.py
tests/test_full_configs/test_shape_variations/config_allvars_Run2.py

Fixed only_variation filter in hist_manager
