lib/cut_definition.py, lib/cut_functions.py, parameters/cuts/baseline_cuts.py, runner.py, utils/Configurator.py
The configuration is dumped in the output folder in two formats. 
- json: Only the cut function name and parameters are retained, not the full object. 
- pickle: the full Configurator object is dumped and it may be directly used to run again. 
Now the outputdir can be overwritten by the runner.py options.
=> Created new json and pickled configuration output

lib/scale_factors.py, parameters/lepton_scale_factors.py, parameters/pileup.py, workflows/base.py
The electron scale factors are read from the json files as recommended by [EGamma](https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaSFJSON), the reconstruction and ID scale factors are computed per-electron and a final per-event weight is computed as the product of the single electron weights and included in the set of applied per-event weights.
Together with the nominal weights, also the weights corresponding to the up and down variations are returned, obtained by varying up and down the electron SF by 1 sigma:
```
sf_reco [1, 0.972, 0.994, 0.985, 0.996, 0.996, ... 0.979, 0.986, 1, 0.992, 0.999, 0.989]
sfup_reco [1, 1.01, 1.01, 1.01, 1.01, 1.01, 1, 1, ... 1.01, 1.01, 1, 1.01, 1, 1.01, 1.02, 1]
sfdown_reco [1, 0.993, 0.987, 0.988, 0.995, 0.995, ... 0.997, 0.994, 1, 0.988, 0.977, 0.996] …
```
=> Electron id and reco SF

.gitignore, PocketCoffea/lib/pileup.py, PocketCoffea/workflows/base.py, config/example.py, config/test_pileup.py, config/test_pileup_variations.py
The computation of pileup weights is now defined in a dedicated library, in order to keep the base processor clean.
Additionally, the config files are updated to adapt to the new implementation of the `Configurator`.
=> Dedicated library for pileup reweighting

PocketCoffea/lib/scale_factors.py, PocketCoffea/parameters/lepton_scale_factors.py, PocketCoffea/workflows/base.py
The computation of the weights associated with the muon identification and isolation cut are included in the framework, and applied to Monte Carlo. The scale factors are computed for each muon and two per-event scale factors (`sf_mu_id` and `sf_mu_iso`) are derived by multiplying the scale factors of all the muons in the event.
As in the electron case, two dedicated weights are included in the `Weights()` object and therefore the muon weights are properly taken into account when histograms are filled.
Together with the "nominal" scale factors, also the "up" and "down" variations are stored, allowing future studies on the variation of the corresponding systematic uncertainties.
=> Implementation of muon id and iso scale factors

PocketCoffea/lib/HistManager.py, PocketCoffea/parameters/histograms.py, PocketCoffea/utils/Configurator.py, PocketCoffea/utils/Plot.py, PocketCoffea/utils/PlotEfficiency.py, PocketCoffea/workflows/base.py, PocketCoffea/workflows/semileptonic_triggerSF.py, config/semileptonic_triggerSF/functions.py, config/semileptonic_triggerSF/semileptonic_triggerSF_2018.py, runner.py, scripts/plot/trigger_efficiency.py
The present PR re-implements the semileptonic trigger SF library in order to migrate from `Coffea` histograms to `hist` histograms.
=> Migration of semileptonic trigger SF library to hist

pocket_coffea/utils/dataset.py
Two bugfixes in the dataset handling are implemented:
- Additional optional parameter `dbs_instance` that can be specified in the metadata for datasets with DBS instance different from `prod/global`
- Bug that was saving a fictious sample dictionary with key `metadata`
Example of `datasets_definition.json` file:
```
{
"DATA_BTagMu":{
"sample": "DATA",
"json_output"     : "datasets/DATA_BTagMu.json",
"storage_prefix" : "/pnfs/psi.ch/cms/trivcat/store/user/mmarcheg/BTVNanoCommissioning",
"files":[
{ "das_names": ["/BTagMu/mmarcheg-Run2018A-UL2018_MiniAODv2-v1_PFNanoAOD-690f1d1c4f2456484a2616002f2d2b6d/USER"],
"dbs_instance" : "prod/phys03",
"metadata": {
"year":"2018",
"isMC": false,
"primaryDataset": "BTagMu",
"era": "A" }},
}
}
```
=> Bugfixes in build_dataset.py

config/test_subsamples.py, pocket_coffea/lib/columns_manager.py, pocket_coffea/lib/hist_manager.py, pocket_coffea/parameters/xsec.py, pocket_coffea/utils/configurator.py, pocket_coffea/utils/dataset.py, pocket_coffea/workflows/base.py, pocket_coffea/workflows/tthbb_base_processor.py, scripts/runner.py
Cleaned up the subsample implementation in the configurator and base processor. 
Histograms selection is done by **parent** sample for the moment. Instead, the column accumulator code is able to differentiate between subsamples in the configuration.  See `test_subsamples.py` configuration file.
=> Cleaning up the subsample implementation

config/btagSF_checks/btag_check_oneside.py, pocket_coffea/lib/scale_factors.py, pocket_coffea/lib/weights_manager.py
The variation of the btagSF were filled in the wrong way because of the c-flavour masks.
The light flavour variations were filled with 1 instead of the **nominal btagSF** when the `cferr*` variations were computed. 
This was causing one-sided uncertainty bands for cferr variations. 
N.B.: Implemented the btagSF central value for JES variations.
=> BugFix for btagSF variation

pocket_coffea/lib/hist_manager.py, pocket_coffea/lib/weights_manager.py, pocket_coffea/workflows/tthbb_base_processor.py
The histogram filling has been speed up by caching the broadcasted weights, when the weights are event-level and the data_structure is 1-D. 
Moreover profiling the filling I observed that the `hist.fill()` method is much faster then we pass numpy arrays instead of awkward arrays. I have included a `to_numpy` while caching the variables to fill. 
This PR brings a ~30% speedup in the histogram filling phase, which with >10 categories can save quite a lot of time.
=> Weights caching and column to_numpy to speedup histogram filling

notebooks/SumGenWeights.ipynb, pocket_coffea/lib/columns_manager.py, pocket_coffea/lib/cut_functions.py, pocket_coffea/lib/hist_manager.py, pocket_coffea/lib/weights_manager.py, pocket_coffea/utils/configurator.py, pocket_coffea/utils/dataset.py, pocket_coffea/workflows/base.py, pocket_coffea/workflows/tthbb_base_processor.py, scripts/runner.py, setup.cfg
In order to be able to rescale automatically the histograms without precomputing the sum of the genweights, we had restructured the output of the processor to save histograms by `dataset` instead of already regrouping by sample in the processor. 
The datasets and samples (subsamples) handling has been improved. 
A `datasets_metadata` dictionary has been added in the output to make easier the regrouping of the histograms at plotting/handling level. 
N.B: **The year is no more an axis in the histograms**. Since each dataset is already split by year, there is no need to create a year axis. The year metadata for each dataset is saved in `datasets_metadata`, but it is not manipulated otherwise.
=> Working on improving sumgenweights and subsamples handling

pocket_coffea/lib/deltaR_matching.py
Two extra metric functions are included in order to compute the $\Delta\eta$ and $\Delta\phi$ distance between objects.
=> Define new metrics for matching

pocket_coffea/lib/scale_factors.py, pocket_coffea/lib/weights_manager.py
A small change is made to the `WeightsManager` to account for the transition from the old parametrization scheme to the fully YAML based parametrization.
The parameters passed to the `sf_btag()` functions are updated accordingly.
=> B-tag weights in YAML scheme

pocket_coffea/utils/plot_utils.py, scripts/plot/make_plots.py
Fixing a bug introduced in my previous commit:
when the `rescale_samples` is not present in the config, plotting script was crashing. This is fixed here
=> Fix crash due to missing rescale_sample parameter in plotting

pocket_coffea/lib/jets.py, pocket_coffea/parameters/histograms.py, pocket_coffea/utils/dataset.py, pocket_coffea/utils/plot_utils.py, pocket_coffea/utils/rucio.py, scripts/plot/make_plots.py, scripts/runner.py, tests/test_package.py
Here is a description of the changes in the order of appearance:
* `jets.py`: allow for jets sorting based on CvsL score
* `histograms.py`: add CvsL and CvsB scores in the default list of histograms for jets
* Also adding a counter on the axis label to distinguish distributions when saving multiple objects (jet 1, 2, 3 etc).
* `dataset.py`: just adding one more check for valid dataset names I stumbled upon. And raising Exception
*  `plot_utils.py`: if a sample specified in the `group_samples` in the config does not exist - the plotting would crash. This fix avoids the crash.
* `rucio.py`: printing a warning that `.sites_map.json` already exists. I encountered an issue that one T2 site has changed their xrootd prefix and so code crashed.  It took me a while to figure out that the reason …
=> Adding jet C-tagging, improving Parsl runner, logger, and minor bugfixes

setup.cfg
Let's add these pins and see if the ci can create docker containers.
We absolutely need hist >= 2.6.1 because that's when the dask interface was added.
We also need dask-histogram>=2024.2.0 because https://github.com/dask-contrib/dask-histogram/pull/120 reduces the graph sizes significantly.
In principle, a lot of these dependencies can be removed and we can rely on coffea for the correct uproot/awkward/dask-stuff dependencies.
=> fix: add hist/dask-histogram pins

pocket_coffea/lib/columns_manager.py, pocket_coffea/lib/cut_functions.py, pocket_coffea/lib/jets.py, pocket_coffea/parameters/btagging.yaml, pocket_coffea/parameters/lepton_scale_factors.yaml, pocket_coffea/workflows/base.py, pocket_coffea/workflows/tthbb_base_processor.py
The scheme for b-tagging parameters is updated to support multiple working points of b-tagging:
- The b-tagging working points for Run-2 have been updated to the latest recommendation from the BTV-POG (https://btv-wiki.docs.cern.ch/PerformanceCalibration/#working-points).
- The Run-3 parameters are updated according to the latest recommendation for the DeepJet tagger. If another tagger has to be used, the user needs to define their custom tagger and working points parameters to override the defaults.
- A key `reference` is included in the b-tagging parameters in `btagging.yaml` to trace the source of the parameters. This entry needs to be updated whenever the WPs are updated and helps the user to keep track of the origin of the defaults.
- The function to apply b-tagging in the processor …
=> Improved b-tagging parameters

pocket_coffea/executors/executors_RWTH.py, pocket_coffea/lib/cut_functions.py, pocket_coffea/lib/leptons.py, pocket_coffea/lib/scale_factors.py, pocket_coffea/parameters/event_flags.yaml, pocket_coffea/parameters/executor_options_defaults.yaml, pocket_coffea/parameters/jet_scale_factors.yaml, pocket_coffea/parameters/lepton_scale_factors.yaml, pocket_coffea/parameters/lumi.yaml, pocket_coffea/parameters/pileup.yaml
Added some new defaults for Run3:
1.  PUid: Added 2022/2023 periods in `pocket_coffea/parameters/pileup.yaml`
2. Lumi: Corrected the defaults in `pocket_coffea/parameters/lumi.yaml` according to the current recommentations (with normtag, see [here](https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3))
3. Added feature, that iso cut on electrons is not needed to be given in params, since current recommendation includes no iso cut on electrons, since mva ID includes iso information
4. sf_ele_reco/id: 
- Changed mapping of params for electron id/reco sfs, since pt_regions are different for Run3 and therefore depend on the year
- Adapted `sf_ele_reco` function to account for the changes and enable more than 2 pt_regions
- Cross checked implementation for 2018, seems to give same …
=> Run3 sf defaults additions

pocket_coffea/parameters/lepton_scale_factors.yaml
Addition of the proper mappins of the lepton ID name in NanoAOD to the naming in the correctionlib set provided by EGM for the Run2 UL working points.
=> Adding Run2 sf_ele default mappings

pocket_coffea/lib/scale_factors.py
Simple change to make Muon SFs work again. The POG unified the corrections for Run2 and Run3, now year/era is not needed anymore. It is defined by the correction file itself.
=> Update Mu SFs for latest convention from POG

pocket_coffea/__init__.py, pocket_coffea/__main__.py, pocket_coffea/parameters/executor_options_defaults.yaml, pocket_coffea/scripts/dataset/build_datasets.py, pocket_coffea/scripts/dataset/dataset_query.py, pocket_coffea/scripts/merge_outputs.py, pocket_coffea/utils/dataset.py, pocket_coffea/utils/rucio.py, setup.cfg
The dataset discovery CLI interface has been implemented in coffea calVer for easy lookup of datasets and replicas in a interactive interface. 
I have added it back in PocketCoffea making it compatible with the `dataset_definition.json` format. 
In practice it can be used to dynamically lookup and build a dataset definition file.
=> Added back the dataset discovery cli in PocketCoffea

docs/analysis_example.md, docs/running.md, pocket_coffea/scripts/runner.py
`--full` renamed to `--process-separately`
docs updated
new name better reflects its purpose
it is clear that the `--full` (now --process-separately) and `--test` option are not related
=> change run option

docs/analysis_example.md, docs/datasets.md, pocket_coffea/scripts/dataset/build_datasets.py, pocket_coffea/utils/build_jets_calibrator.py, pocket_coffea/utils/dataset.py, pocket_coffea/utils/rucio.py
This introduces  a new feature in `build_datasets` script, which allows to use INFN redirector prefix in cases when no white-listed sites were found f or a given file (using the `-ws` option). At the moment a Warning is printed when this happens, which may be suppressed in the future.
My use case is the following. Most of the datasets are copied to some German T2s but not all of them. I want to preference those sites, but when the sample is not there, just use the redirector:
```
build_datasets --cfg samples.json -o -ws T2_DE_RWTH  --use-infn
```
The behavior should be the same as before, when the flag is not used.
=> Allow INFN redirector to be used when no sites are found with -ws option

pocket_coffea/executors/executors_cern_swan.py, pocket_coffea/scripts/runner.py
The CERN Swan executor uses the Dask scheduler created by the Swan interface and connects to that.
=> Preparing executor for CERN Swan

pocket_coffea/utils/configurator.py, pocket_coffea/workflows/base.py
SumGenWeight is used for weight rescaling only if `genWeight` or `signOf_genWeight` is used in the `inclusive` weights configuration for the sample.
=> Removed application of sumgenweight rescaling by default

pocket_coffea/scripts/runner.py, pocket_coffea/utils/configurator.py
The configurator constructor was initializing the Configurator but also loading all the necessary data from the dataset configuration. 
This PR separates the construction and loading the the Configurator to allow users to load the Configurator object to look at options,metadata, parameters, without having to load the actual datasets to begin the processing. 
This allows law to inspect the Configurator before the dataset files are defined.
@felixzinn
=> Separated init and loading in the Configurator

pocket_coffea/__main__.py, pocket_coffea/parameters/defaults.py, pocket_coffea/scripts/print_parameters.py, pocket_coffea/scripts/runner.py, pocket_coffea/utils/configurator.py, pocket_coffea/utils/utils.py, pyproject.toml
A new command `pocket-coffea print-parameters` is added to explore somehow dynamically the parameters attached to a configuration. 
The end user usually overwrite existing default metadata, but getting to know the value of the default metadata requires looking at the central repo files or looking at the parameters_dump of a pocket-coffea run. 
With this new tool the user can explore the parameters, dump them locally, to cross-check his own configuration (default + custom parameters) before running. 
-------------
```
pocket-coffea) ➜  zmumu git:(main) ✗ pocket-coffea print-parameters -c example_config.py --cli
____             __        __  ______      ________
/ __ \____  _____/ /_____  / /_/ ____/___  / __/ __/__  ____ _
/ /_/ / __ \/ ___/ //_/ _ \/ __/ /   / __ \/ /_/ /_/ _ \/ __ `/
/ …
```
=> New parameters exploration tool

pocket_coffea/workflows/base.py
wrong syntax for check of `"genWeight"` and `"signOf_genWeight"` in weights config. genWeights have not been applied to the histograms
old syntax 
```python
elif "genWeight" in wei and not "signOf_genWeight":
sumgenw_dict = output["sum_genweights"]
```
the `not "signOf_genWeight"` always evaluates to `False`, so histograms are not rescaled
changed to
```python
elif "genWeight" in wei and "signOf_genWeight" not in wei:
sumgenw_dict = output["sum_genweights"]
```
=> fix check of genWeight in weights config

pocket_coffea/lib/jets.py, pocket_coffea/lib/scale_factors.py, pocket_coffea/utils/configurator.py
Minor improvements to the framework:
- Argument to veto the b-tagging requirement using the `btagging()` function, to select light jets
- Update single electron trigger SF function for Run-2 retrocompatibility
- Fix configurator to save columns with subsamples
=> Various improvements

pocket_coffea/lib/hist_manager.py, pocket_coffea/lib/weights_manager.py
Wildcard weights variations (like btagSF) taken from parameters are handled by the weights manager. 
The wildcard was not solved correctly by the hist_manager.
=> Fixed wildcard weights variation implementation 

docs/analysis_example.md, pocket_coffea/lib/cut_functions.py, pocket_coffea/workflows/base.py
Removed default skim cuts from base processor and defined corresponding cut objects in the `cut_functions` lib. 
- nPV_good > 0 selection
- goldenJson
- event flags
Solves #104
=> Removed default skim cuts from base processor

docs/plots.md, pocket_coffea/parameters/variations.yaml, pocket_coffea/utils/plot_utils.py
This will enable to blind some data distributions in Signal regions.
This addresses issue #175 
Documentation is also updated.
Also adding missing default values in variations for 2022/2023 eras.
=> Enable blinding data for certain histograms

docs/plots.md, pocket_coffea/parameters/plotting_style.yaml, pocket_coffea/utils/plot_utils.py
This allows for plotting signal sample histogram outside of the MC stack, and scale them. 
Also, enabling to print category name and year on the plots (not printed by default).
Here is an example from my analysis:
PS. Some empty lines are removed due to running a command in emacs to remove white spaces.
@valsdav this is ready to be reviewed.
=> feat: plot separate histogram for signal samples, print category name

pocket_coffea/utils/plot_utils.py
This is a minor fix for #214 :
when the `signal_samples` is present in the config but the `labels_mc` is not present, it would crash. With this change, it will work.
=> Bug fix for signal samples plotting

pocket_coffea/scripts/runner.py
A change in the `runner.py` script is needed to import paths when the `executor_custom_setup` feature is used.
The change is needed in the `stable` branch while it is already fixed in the `main` branch.
=> Fix import with custom executor setup

docs/installation.md, docs/plots.md, pocket_coffea/parameters/plotting_style.yaml, pocket_coffea/scripts/merge_outputs.py, pocket_coffea/scripts/plot/make_plots.py, pocket_coffea/utils/plot_utils.py
New features:
- **Bugfix:** Correct computation of underflow and overflow bins in MC and systematic uncertainty
- **Bugfix:** Improved defaults for the `Style` class and sanity checks
- **Enhancement:** Generalization of the categorical axes parameters for data and MC with defaults
- **Docs:** Updated documentation
**Correct underflow and overflow bins**
The computation of the MC yield and systematic uncertainty for the underflow and overflow bins is now correctly computed. The underflow and overflow bins are correctly summed to the first and last bin respectively.
The present default is that the user has to set both `underflow` and `overflow` axis parameters to the same value, i.e. the configurations with `underflow=True` and `overflow=False` and viceversa are not supported. However, …
=> Correct under/overflow bins

pocket_coffea/executors/executors_infn_af.py
This PR introduces a couple of try except to better handle the case in which you are reusing a preexisting Dask cluster in which proxyfile has been already uploaded and its permissions already modified.
=> Update executors_infn_af.py to better handle already configured Dask cluster

.gitignore, pocket_coffea/lib/deltaR_matching.py, pocket_coffea/lib/gen_objects.py, pocket_coffea/lib/jets.py, pocket_coffea/lib/leptons.py, pocket_coffea/lib/objects.py, pocket_coffea/parameters/histograms.py, pocket_coffea/parameters/plotting_style.yaml, pocket_coffea/utils/plot_utils.py
Adding some tools for generator-only analysis. Namely, selecting leptons from GenParticles and selecting GenJets
Plus, a few  other minor changes: `delta_phi` function; new histograms for gen objects, new histograms for PNet and RobustParT tagger scores; minor changes for plotting with --compare option.
=> Basic methods to deal with GenParticles and GenJets, and more tagger options for Jets

pocket_coffea/lib/parton_provenance.py
Added a function to assign provenance values to b-quarks in dileptonic ttH -> bb events.  The function handles the Higgs decay b-quarks (1), top quark b-quark (2), anti-top b-quark (3), and additional radiation (4) when present. It updates the array_builder with the provenance for each event.
=> Assign provenance to b-quarks in ttHbb dileptonic decays

pocket_coffea/executors/executors_cern_swan.py, pocket_coffea/parameters/executor_options_defaults.yaml, pocket_coffea/parameters/histograms.py, pocket_coffea/scripts/hadd_skimmed_files.py, pocket_coffea/scripts/runner.py, pocket_coffea/utils/rucio.py, pocket_coffea/utils/time.py
- Solved https://github.com/PocketCoffea/PocketCoffea/issues/258: fixed missing default for histograms name.
- Solved https://github.com/PocketCoffea/PocketCoffea/issues/259: avoid concurrent read/writes to `.sites_map.json` using multiprocessing locks.
- Enhancement in `runner.py`: schedule job submission at a given time specified in the run options.
- Update `hadd_skimmed_files.py`: save complete metadata of skimmed datasets with size, number of events and skimmed efficiency. Save the `isSkim` metadata to flag that the dataset is a skim.
=> Improved scripts

pocket_coffea/scripts/hadd_skimmed_files.py
We noticed that hadd is silently failing and excluding files when branches are missing in one of the inputs. This is happening often while joining Data files (same era) wich may have different HLT branches. 
Solution for #289 :
- replaced hadd with TChain
- added job submission
=> fix: hadd for skimmed files

pocket_coffea/lib/scale_factors.py, pocket_coffea/lib/weights/common/common.py, pocket_coffea/lib/weights/common/weights_run2_UL.py, pocket_coffea/utils/configurator.py
The generator level weights to account for the variation of the QCD scale both in the hard process and in the parton shower (PS) are implemented. In particular, the following weights are implemented:
- PS weight to vary up/down the QCD renormalization scale in the initial-state-radiation (ISR) parton shower
- PS weight to vary up/down the QCD renormalization scale in the final-state-radiation (FSR) parton shower
- Weight to vary up/down the QCD renormalization scale ($\mu_R$) in the hard process
- Weight to vary up/down the QCD factorization scale ($\mu_f$) in the hard process
The weights are taken from the generator-level variables `PSWeight` and `LHEScaleWeight`.
Since the implementation of the PS weights is compatible both with NanoAODv9 and NanoAODv12, it is included in the common …
=> Parton shower and QCD scale weights

pocket_coffea/utils/rucio.py
The PR fixes the confusion after blocksites list. Often users don't put the suffix `_Disk` while filtering for some sites. 
Now that is checked automatically.
=> fix: automatically remove _Disk from sitename when filtering

pocket_coffea/law_tasks/tasks/datasets.py, pocket_coffea/law_tasks/utils.py, pocket_coffea/parameters/defaults.py
some minor updates on the plotting task
`parameters/defaults.py`: syntax error fixed
`law_tasks/utils.py`: if a custom_plot_style file is passed to the plotting task, it would not take into account all changes, e.g. if `samples_groups` in the new custom_plot_style file had fewer entries, then the merging with `update=True` leads to the old entries still being in the yaml file
```yml
plotting_style:
samples_groups:
group1:
- sample1
- sample2
```
group2 is commented out in the custom_plot_style but kept in the plotting since, it is in the original plotting.yaml and only updated
`law_tasks/tasks/datasets.py`: the output path of the datasets are set in the configurator, cannot be changed by law task --> fixed
=> Minor-update on plotting and law tasks

datasets/README.md, docs/datasets.md, pocket_coffea/law_tasks/tasks/datasets.py, pocket_coffea/scripts/dataset/build_datasets.py, pocket_coffea/scripts/dataset/dataset_query.py, pocket_coffea/utils/dataset.py, pocket_coffea/utils/rucio.py
This is a small addition to the sorting options in `build_dataset` and `dataset-discovery-cli`
In particular:
- adds an additional sorting option (additional to the recently added `geoip`) called `priority`
- provides option to give a list of prioritised sites using `prioritylist-sites` (similar to for instance `blocklist-sites`) (flag is `-ps`)
- for `build-dataset` this means, that if available, first priority is chosen, if not available second and so on. If no prioritised site is available, default behaviour is applied.
- in `dataset-discovery-cli`, replicas of files are then ordered such that prioritised sites are listed on top if available the rest of the sites are still ordered according to default.
Solves issue https://github.com/PocketCoffea/PocketCoffea/issues/225
-- Additional …
=> Priority sorting in `build-dataset` and `dataset-discovery-cli`

pocket_coffea/utils/dataset.py, pocket_coffea/utils/rucio.py
It could happen sometimes that a Valid dataset contains a few invalid files.
Example in `/Zto2Nu-2Jets_PTNuNu-200to400_2J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v1/NANOAODSIM` dataset, where one file is invalid.
Rucio does not know about invalid file, but DAS knows.
This PR allows to filter such files.
=> Filter invalid files in a dataset

pocket_coffea/scripts/runner.py
Small fix to enable `run --test` runs with `save_skimmed_files` on.
If running `pocket-coffea run ...` with `save_skimmed_files` defined in the `Configurator()`, PocketCoffea is comparing the amount of initial events in the metadata with the amount of initial events in the cutflow ([here](https://github.com/PocketCoffea/PocketCoffea/blob/main/pocket_coffea/utils/skim.py#L97)).
When running with the `--test` flag enabled, this will generally throw an exception, because in this case only 2 files will be read in leading to a smaller array of events.
The fix will now skip this check if running with `--test` activated.
=> Prevent save_skimmed_files from failing with --test

docs/installation.md, pocket_coffea/executors/executors_lxplus.py
**Add feature `--recreate-jobs auto`**
- Support specifying `--recreate-jobs auto` instead of `--recreate-jobs 1,2,3`.
- Automatically create list based on available `job_n.failed` files.
**Find alternative XRootD site (`--recreate-jobs`)**
- Detect if a job failed due to an XRootD error: parse job's `.err` for "XRootD Error".
- For such jobs, find an alternative XRootD site *during resubmission*.
- Update `.pkl` of such jobs with new list of files.
**Formatting changes**
- Moved `get_worker_env` function outside the dask and condor classes to avoid duplication of code.
**Change queue for evicted jobs (`--recreate-jobs`)** (new commit):
- Check if the job is still left marked as `running` and bump their queue before resubmission (same behaviour as `scripts/check_jobs.py`)
**Update to …
=> condor@lxplus: Automatic selection of failed jobs while resubmitting; backup xrootd site for xrootd errors

pocket_coffea/utils/plot_utils.py
I think the `check_empty_variations()` is bugged, when it tries to compare the nominal and variations hist.
This is a fix.
=> Fix an empty variations check

docs/recipes.md, pocket_coffea/executors/executors_lxplus.py, pocket_coffea/parameters/executor_options_defaults.yaml, pocket_coffea/scripts/merge_outputs.py, pocket_coffea/scripts/plot/make_plots.py, pocket_coffea/scripts/split_output.py, pocket_coffea/utils/filter_output.py, pocket_coffea/utils/plot_utils.py
The main feature addition is splitting outputs into different categories so that large .coffea files need not be handled in memory during plotting. This enables analyses that have many categories which makes the `merge-output` script fail.
New features:
**`condor@lxplus` executor:**
- ~~Unfortunately some overlaps with #358~~ Resolved
- `--split-by-category` option which splits `output_all.coffea` into several chunks, each containing disjoint set of 8 categories. It calls `split-output`, which now has a new feature `--by category`, which in turn calls another new function, `utils.filter_output.filter_output_by_category`.
**Thoughts:** Coding-wise, this would be easier and more natural to handle by directly calling `utils.filter_output.filter_output_by_category` on `output` within …
=> Add split-by-category feature for handling large outputs with histograms from a large number of categories

pocket_coffea/scripts/check_jobs.py
Two main features:
1. For failed files, check the .err to see if there was an XRootD error. In that case, find an alternative XRootD site for the failed file and replace it. Keep a log of XRootD failed paths on disk and avoid them if a second site fails for the same file.
2. If a site records a large number of failed files (10 by default), replace all files from that site within the current config of a failed job and don't use it in future file replacements. Keep a log of blacklisted sites on disk.
Others:
1. Also look into idle jobs when checking aborted job list. Re-resubmission of newly idle jobs is prevented by maintaining a log of resubmitted jobs on disk. 
2. Other minor logging changes. 
Just one caveat:
I could not fully test the blacklist enforcement because all CMS sites are …
=> check-jobs: Replace files with xrootd errors; implement blacklist for sites with repeated failures

pocket_coffea/lib/calibrators/calibrator.py, pocket_coffea/lib/calibrators/calibrators_manager.py, pocket_coffea/lib/calibrators/common/common.py, pocket_coffea/workflows/base.py, tests/test_calibrators.py
added `do_variation` argument to Calibrator to signal to the initialization function is the variation will be actually used or not. 
This is propagated from the configuration to the CalibratorsManager. This can be useful to avoid computing the JEC variations if they are not used. 
FYI @phnattla
=> Propagate variations config to Calibrators
